// iBarti V1 Exchange-Type architecture.
// Three top-level Exchange Types; a 24-category V1 tree under them; each
// category declares which exchange types it belongs to and its subcategories.
// Existing category IDs are preserved so saved listings keep resolving.
//
// Subcategories are stored as short slugs; the full i18n key is
// `${categoryId}__${subSlug}` and labels live in the `v1sub` block of the
// i18n dictionary (translated for EN/ES/FR/AR and auto-generated by the LLM
// for every other language the UI supports). Listings store the full key in
// have_subcategory / want_subcategory so the label resolves to the current
// UI language everywhere it is rendered.

export const EXCHANGE_TYPES = [
  { id: 'goods', icon: '📦' },
  { id: 'services', icon: '🛠' },
  { id: 'digital', icon: '💻' }
];

export const EXCHANGE_TYPE_IDS = EXCHANGE_TYPES.map((x) => x.id);

// 24-category V1 tree — broad enough that subcategories together cover
// virtually anything someone could barter.
// `exchange_types` lists which top-level types a category can appear under.
// `subcategories` is the ordered list of V1 subcategory slugs (localizable).
export const CATEGORY_TREE = [
  {
    id: 'electronics_technology',
    exchange_types: ['goods', 'digital'],
    subcategories: ['phones', 'laptops', 'desktops', 'tablets', 'cameras_photo', 'audio_sound', 'gaming', 'tvs_displays', 'smart_home', 'wearables', 'components_parts', 'accessories']
  },
  {
    id: 'home_furniture',
    exchange_types: ['goods'],
    subcategories: ['furniture', 'home_decor', 'kitchen_dining', 'large_appliances', 'small_appliances', 'lighting', 'bedding', 'bathroom', 'storage_org', 'rugs_textiles']
  },
  {
    id: 'fashion_personal',
    exchange_types: ['goods'],
    subcategories: ['clothing', 'shoes', 'bags', 'watches', 'jewelry', 'eyewear', 'hats_accessories', 'costume', 'vintage_fashion', 'kids_fashion']
  },
  {
    id: 'beauty_wellness',
    exchange_types: ['goods', 'services'],
    subcategories: ['skincare', 'haircare', 'makeup', 'fragrance', 'spa_treatments', 'hair_services', 'beauty_sessions', 'grooming']
  },
  {
    id: 'books_education',
    exchange_types: ['goods', 'digital'],
    subcategories: ['books', 'textbooks', 'magazines', 'comics_manga', 'study_materials', 'online_courses', 'learning_toys', 'stationery']
  },
  {
    id: 'creative_design',
    exchange_types: ['services', 'digital'],
    subcategories: ['graphic_design', 'illustration', 'photography', 'video_film', 'animation', 'writing_copywriting', 'editing', 'music_production', 'handmade_art', 'crafts']
  },
  {
    id: 'digital_online_services',
    exchange_types: ['services', 'digital'],
    subcategories: ['web_development', 'app_development', 'software_apps', 'seo', 'digital_marketing', 'social_media', 'virtual_assistance', 'cloud_hosting', 'domains_accounts']
  },
  {
    id: 'repairs_practical',
    exchange_types: ['services'],
    subcategories: ['electrical', 'plumbing', 'carpentry', 'electronics_repair', 'computer_repair', 'phone_repair', 'appliance_repair', 'vehicle_repair', 'handyman', 'painting', 'moving_help']
  },
  {
    id: 'business_professional',
    exchange_types: ['services', 'digital'],
    subcategories: ['consulting', 'marketing', 'accounting', 'legal', 'hr_recruitment', 'translation_services', 'research', 'grant_writing', 'admin_support']
  },
  {
    id: 'vehicles_transport',
    exchange_types: ['goods', 'services'],
    subcategories: ['cars', 'motorcycles', 'scooters', 'bicycles', 'auto_parts', 'tires_wheels', 'transport_services', 'delivery', 'shipping']
  },
  {
    id: 'sports_hobbies',
    exchange_types: ['goods'],
    subcategories: ['sports_equipment', 'fitness_gear', 'outdoor_camping', 'cycling', 'fishing', 'hunting', 'musical_instruments', 'board_games', 'hobby_supplies']
  },
  {
    id: 'collectibles_vintage',
    exchange_types: ['goods'],
    subcategories: ['stamps', 'coins', 'antiques', 'memorabilia', 'vintage_electronics', 'trading_cards', 'vinyl_records', 'comic_books', 'art_collectibles']
  },
  {
    id: 'food_garden_homemade',
    exchange_types: ['goods'],
    subcategories: ['baked_goods', 'preserves', 'plants', 'seeds', 'home_grown_produce', 'honey', 'bulk_food', 'beverages']
  },
  {
    id: 'tools_machinery',
    exchange_types: ['goods', 'services'],
    subcategories: ['power_tools', 'hand_tools', 'workshop', 'machinery', 'construction', 'industrial', 'farming_tools']
  },
  {
    id: 'health_medical',
    exchange_types: ['goods', 'services'],
    subcategories: ['medical_equipment', 'mobility_aids', 'first_aid', 'therapies', 'counseling', 'fitness_training', 'nutrition']
  },
  {
    id: 'kids_baby',
    exchange_types: ['goods'],
    subcategories: ['toys', 'baby_gear', 'kids_clothing', 'kids_furniture', 'educational_toys', 'games', 'school_supplies', 'strollers_carriers']
  },
  {
    id: 'pets_animals',
    exchange_types: ['goods', 'services'],
    subcategories: ['pet_food_supplies', 'pet_accessories', 'enclosures', 'pet_care_services', 'pet_grooming', 'training', 'animals_livestock']
  },
  {
    id: 'real_estate_housing',
    exchange_types: ['goods', 'services'],
    subcategories: ['rentals', 'rooms_shares', 'parking', 'storage', 'renovation', 'furniture_items', 'estate_services']
  },
  {
    id: 'media_entertainment',
    exchange_types: ['goods', 'digital'],
    subcategories: ['movies', 'music', 'video_games', 'streaming_accounts', 'software_licenses', 'ebooks', 'digital_art', 'audiobooks']
  },
  {
    id: 'office_stationery',
    exchange_types: ['goods'],
    subcategories: ['office_supplies', 'stationery_office', 'printers', 'ink_toner', 'office_furniture', 'filing', 'labels']
  },
  {
    id: 'events_hospitality',
    exchange_types: ['services', 'goods'],
    subcategories: ['event_planning', 'catering', 'venues', 'event_photography', 'hospitality', 'lodging', 'travel_hosting']
  },
  {
    id: 'travel_experiences',
    exchange_types: ['services', 'digital'],
    subcategories: ['accommodation', 'tours', 'experiences', 'travel_planning', 'ticketing', 'travel_swaps']
  },
  {
    id: 'agriculture_farming',
    exchange_types: ['goods', 'services'],
    subcategories: ['crops', 'livestock', 'feed', 'seeds_saplings', 'farming_equipment', 'land_share', 'farming_services']
  },
  {
    id: 'other_mixed',
    exchange_types: ['goods', 'services', 'digital'],
    subcategories: ['mixed_lots', 'barter_bundles', 'miscellaneous', 'unclassified']
  }
];

export const CATEGORY_IDS = CATEGORY_TREE.map((c) => c.id);

export const getCategory = (id) => CATEGORY_TREE.find((c) => c.id === id);

// Categories available under a given exchange type.
export const categoriesForType = (typeId) =>
  CATEGORY_TREE.filter((c) => c.exchange_types.includes(typeId));

// Full i18n key for a subcategory (stable, stored on the listing).
export const subcatKey = (categoryId, subSlug) => `${categoryId}__${subSlug}`;

// Sentinel stored on listings when the user picks the generic "Other"
// fallback at either the category or the subcategory level.
export const OTHER_KEY = '__other';

// Resolve a stored category id into the current UI language's label,
// including the "Other" sentinel and legacy free-form text.
export const categoryLabel = (t, catId) => {
  if (!catId) return '';
  if (t.v1cat && t.v1cat[catId]) return t.v1cat[catId];
  if (catId === OTHER_KEY) return (t.listing && t.listing.otherCategory) || 'Other';
  return catId;
};

// Resolve a stored subcategory value into the current UI language's label.
// Handles the "Other" sentinel, localizable keys, and legacy free-form text.
export const subcatLabel = (t, stored) => {
  if (!stored) return '';
  if (stored === OTHER_KEY) return (t.listing && t.listing.otherSubcategory) || 'Other';
  if (t.v1sub && t.v1sub[stored]) return t.v1sub[stored];
  return stored;
};

export const EXCHANGE_LOCATIONS = ['local', 'national', 'international', 'online'];