// Comprehensive category taxonomy for goods and services.
// Used by CreateListing, Explore, and any other surface that lists categories.
// Translations live in src/lib/i18n.jsx under the `categories` key for each locale.
export const CATEGORY_KEYS = [
  // Goods
  'electronics',
  'computers',
  'phones',
  'camera',
  'audio',
  'gaming',
  'furniture',
  'home',
  'kitchen',
  'garden',
  'tools',
  'appliances',
  'clothing',
  'footwear',
  'accessories',
  'jewelry',
  'beauty',
  'books',
  'media',
  'music',
  'art',
  'crafts',
  'collectibles',
  'sports',
  'fitness',
  'outdoors',
  'bicycles',
  'vehicles',
  'toys',
  'baby',
  'kids',
  'pets',
  'office',
  'agriculture',
  'food',
  // Services
  'repairs',
  'maintenance',
  'cleaning',
  'transport',
  'moving',
  'cooking',
  'tutoring',
  'languages',
  'music_lessons',
  'design',
  'writing',
  'translation',
  'it_services',
  'consulting',
  'marketing',
  'photo_video',
  'events',
  'travel',
  'health',
  'wellness',
  'other'
];